version: '3.3'

services:
  db:
    image: mariadb:latest
    volumes:
    - db_data:/var/lib/mysql
    ports:
    - "6596:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
    - db
    image: wordpress:latest
    volumes:
    - ./src/:/var/www/html/
    - ./mu-plugins:/var/www/html/wp-content/mu-plugins
    ports:
    - "6500:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  mailcatcher:
    image: schickling/mailcatcher
    ports:
    - "6525:1025"
    - "6580:1080"

volumes:
  db_data:
